@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZkZjdjNzZhNWYwNzQzMGE2ZGJiM2MiLCJpYXQiOjE3MzU3MzQyNzIsImV4cCI6MTczNTgyMDY3Mn0.9XHxw6In0l9XZF8l0z37Pm18ewVJy9qQ-VCfY1-CKqY


## GET all artists
GET http://localhost:5000/api/artists
Authorization: Bearer {{token}}

### GET an artist
GET http://localhost:5000/api/artists/676de9d8108c545224fb333f
Authorization: Bearer {{token}}


### ADD an artist
POST http://localhost:5000/api/artists
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "image": "image-url",
    "name": "Melchi Loic",
    "stageName": "Bricky",
    "numOfAlbums": 0,
    "recordLabel": "Libra",
    "publishingHouse": "Publishing House Name",
    "startDate": "2023-10-01T00:00:00.000Z"
}

### UPDATE STATUS OF A FRIEND
PUT http://localhost:5000/api/artists/676de9d8108c545224fb333f
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "image": "image-url",
    "name": "Melchi Loic",
    "stageName": "Bricky Invok",
    "numOfAlbums": 2,
    "mediaLinks": [],
    "recordLabel": "Libra",
    "publishingHouse": "Publishing House Name",
    "startDate": "2023-10-01T00:00:00.000Z"
}


###DELETE A FRIEND
DELETE http://localhost:5000/api/artists/676de9d8108c545224fb333f
Content-Type: application/json
Authorization: Bearer {{token}}