@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZkZjdjNzZhNWYwNzQzMGE2ZGJiM2MiLCJpYXQiOjE3MzU3MzQyNzIsImV4cCI6MTczNTgyMDY3Mn0.9XHxw6In0l9XZF8l0z37Pm18ewVJy9qQ-VCfY1-CKqY

## GET all artists
GET http://localhost:5000/api/users
Authorization: Bearer {{token}}

### GET a user
GET http://localhost:5000/api/users/676dee5ca492082befb2031e
Authorization: Bearer {{token}}


### ADD a user
POST http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Maria Mbungai",
  "email": "mbungaimaria@gmail.com",
  "password": "root2",
  "dateofbirth": "1986-12-03T00:00:00.000Z"
}
 
### UPDATE a user
PUT http://localhost:5000/api/users/676dee5ca492082befb2031e
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Mirabele Kiwo",
  "email": "mbungaimirabele@gmail.com",
  "password": "root",
  "dateofbirth": "1986-12-03T00:00:00.000Z"
}


###DELETE A user
DELETE http://localhost:5000/api/users/676dee5ca492082befb2031e
Content-Type: application/json
Authorization: Bearer {{token}}

###Login User
POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "mbungaimirabele@gmail.com",
  "password": "root2"
}